=== 4850-XSL-Lab10/4850Lab10/data/classSchedule.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- Theses are the attribute types we created for the time, and day for the elements -->
    <xs:simpleType name="Ttime">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-2][0-9][0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="HourMinuteTime" id="startTime">
        <xs:restriction base="xs:time">
            <xs:whiteSpace value="collapse" fixed="true"/>
        </xs:restriction>
    </xs:simpleType>

    
    <xs:simpleType name="TcourseID">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-4][0-9][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Tweekday">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- this element represents the schedule structure including the three facets -->
    <xs:element name="schedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="courses" type="Tcourses" maxOccurs="3"/>
                <xs:element name="days" type="Tdays" maxOccurs="3"/>
                <xs:element name="timeslots" type="Ttimeslots" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Complex type (element) for timeslots with the startTime attribute calling 
    type HourMinuteTime declared earlier -->
    <xs:complexType name="Ttimeslots">
        <xs:sequence>
            <xs:element name="timeslot" type="Ttimeslot" maxOccurs="9"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Ttimeslot">
        <xs:sequence>
            <xs:element name="booking" type="Tbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="startTime" type="HourMinuteTime" use="required"/>
    </xs:complexType>
    
    <!-- Complex type (element) for days with the weekDay attribute calling type Tday
    declared earlier -->
    <xs:complexType name="Tdays">
        <xs:sequence>
            <xs:element name="day" type="Tday" maxOccurs="6"/>
        </xs:sequence>
    </xs:complexType>
        
    <xs:complexType name="Tday">
        <xs:sequence>
            <xs:element name="booking" type="Dbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="weekDay" type="Tweekday" use="required"/>
    </xs:complexType>
    
    <!-- Complex type (element) for courses with the courseID attribute calling type TcourseID
    declared earlier -->
    <xs:complexType name="Tcourses">
        <xs:sequence>
            <xs:element name="course" type="Tcourse" maxOccurs="6"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="Tcourse">
        <xs:sequence>
            <xs:element name="booking" type="Cbooking" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="courseID" type="TcourseID" use="required"/>
    </xs:complexType>
    
    
    <!-- Booking attributes for all three facets: Courses, Days, and Timeslots -->
    <!-- Created 3 different bookings with different attributes for three facets -->
    <xs:complexType name="Cbooking">
        <xs:attribute name="weekDay" type="Tweekday" use="required"/>
        <xs:attribute name="startTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="endTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="instructor" type="xs:string" use="required"/>
        <xs:attribute name="classActivity" type="xs:string" use="required"/>
        <xs:attribute name="classLocation" type="xs:string" use="required"/>
    </xs:complexType>
    
     <xs:complexType name="Dbooking">
        <xs:attribute name="courseID" type="TcourseID" use="required"/>
        <xs:attribute name="startTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="endTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="instructor" type="xs:string" use="required"/>
        <xs:attribute name="classActivity" type="xs:string" use="required"/>
        <xs:attribute name="classLocation" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="Tbooking">
        <xs:attribute name="courseID" type="TcourseID" use="required"/>
        <xs:attribute name="weekDay" type="Tweekday" use="required"/>
        <xs:attribute name="endTime" type="HourMinuteTime" use="required"/>
        <xs:attribute name="instructor" type="xs:string" use="required"/>
        <xs:attribute name="classActivity" type="xs:string" use="required"/>
        <xs:attribute name="classLocation" type="xs:string" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== 4850-XSL-Lab10/4850Lab10/data/master.xml
<?xml version="1.0" encoding="UTF-8"?>


<!-- This is the facet structure for all the courses we want displayed -->
<!-- We changed the time standard from hh:mm to hh:mm:ss to work with the schema -->
<schedule 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="classSchedule.xsd">
    <courses>
        <course courseID="4620">
            <booking weekDay="Tuesday" startTime="10:30:00" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking weekDay="Tuesday" startTime="03:30:00" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </course>
        <course courseID="4650">
            <booking weekDay="Monday" startTime="04:30:00" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
            <booking weekDay="Tuesday" startTime="12:30:00" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking weekDay="Tuesday" startTime="01:30:00" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
        </course>
        <course courseID="4660">
            <booking weekDay="Wednesday" startTime="10:30:00" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking weekDay="Friday" startTime="08:30:00" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </course>
        <course courseID="4770">
            <booking weekDay="Monday" startTime="01:30:00" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
        </course>
        <course courseID="4850">
            <booking weekDay="Wednesday" startTime="12:30:00" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
            <booking weekDay="Thursday" startTime="10:30:00" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </course>
        <course courseID="4910">
            <booking weekDay="Monday" startTime="03:30:00" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking weekDay="Thursday" startTime="09:30:00" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking weekDay="Thursday" startTime="01:30:00" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </course>
    </courses>

    <days>
        <day weekDay="Monday">
            <booking courseID="4770" startTime="01:30:00" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseID="4910" startTime="03:30:00" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseID="4650" startTime="04:30:00" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </day>
        <day weekDay="Tuesday">
            <booking courseID="4620" startTime="10:30:00" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4650" startTime="12:30:00" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseID="4650" startTime="01:30:00" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4620" startTime="03:30:00" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </day>
        <day weekDay="Wednesday">
            <booking courseID="4660" startTime="10:30:00" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4850" startTime="12:30:00" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </day>
        <day weekDay="Thursday">
            <booking courseID="4910" startTime="09:30:00" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
            <booking courseID="4850" startTime="10:30:00" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
            <booking courseID="4910" startTime="01:30:00" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </day>
        <day weekDay="Friday">
            <booking courseID="4660" startTime="08:30:00" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </day>
    </days>

    <timeslots>
        <timeslot startTime="08:30:00">
            <booking courseID="4660" weekDay="Friday" endTime="10:20:00" instructor="Steve" classActivity="Lecture" classLocation="SW9-206" />
        </timeslot>
        <timeslot startTime="09:30:00">
            <booking courseID="4910" weekDay="Thursday" endTime="10:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW5-1840" />
        </timeslot>
        <timeslot startTime="10:30:00">
            <booking courseID="4620" weekDay="Tuesday" endTime="12:20:00" instructor="Bethany" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4660" weekDay="Wednesday" endTime="12:20:00" instructor="Steve" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4850" weekDay="Thursday" endTime="12:20:00" instructor="Jim" classActivity="Lab" classLocation="SE12-320" />
        </timeslot>
        <timeslot startTime="11:30:00">
            <booking courseID="4650" weekDay="Tuesday" endTime="01:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseID="4850" weekDay="Wednesday" endTime="02:20:00" instructor="Jim" classActivity="Lecture" classLocation="SW3-1750" />
        </timeslot>
        <timeslot startTime="01:30:00">
            <booking courseID="4770" weekDay="Monday" endTime="03:20:00" instructor="Trevor" classActivity="Tutorial" classLocation="SE12-306" />
            <booking courseID="4650" weekDay="Tuesday" endTime="03:20:00" instructor="Medhat" classActivity="Lab" classLocation="SE12-306" />
            <booking courseID="4910" weekDay="Thursday" endTime="03:20:00" instructor="Richard" classActivity="Lab" classLocation="SE12-306" />
        </timeslot>
        <timeslot startTime="03:30:00">
            <booking courseID="4910" weekDay="Monday" endTime="04:20:00" instructor="Richard" classActivity="Lecture" classLocation="SW9-206" />
            <booking courseID="4620" weekDay="Tuesday" endTime="05:20:00" instructor="Bethany" classActivity="Lecture" classLocation="SW3-3615" />
        </timeslot>
        <timeslot startTime="04:30:00">
            <booking courseID="4650" weekDay="Monday" endTime="05:20:00" instructor="Medhat" classActivity="Lecture" classLocation="SE6-205" />
        </timeslot>
            
    </timeslots>
</schedule>
